
package eu.x_road.us_folk_v3.producer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsFolkService", targetNamespace = "http://us-folk-v3.x-road.eu/producer", wsdlLocation = "file:/C:/_proj/us/folk-v3/folk-v3-api/src/main/resources/fo/us/folkv3/api/client/us-folk-v3.wsdl")
public class UsFolkService
    extends Service
{

    private final static URL USFOLKSERVICE_WSDL_LOCATION;
    private final static WebServiceException USFOLKSERVICE_EXCEPTION;
    private final static QName USFOLKSERVICE_QNAME = new QName("http://us-folk-v3.x-road.eu/producer", "UsFolkService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/_proj/us/folk-v3/folk-v3-api/src/main/resources/fo/us/folkv3/api/client/us-folk-v3.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USFOLKSERVICE_WSDL_LOCATION = url;
        USFOLKSERVICE_EXCEPTION = e;
    }

    public UsFolkService() {
        super(__getWsdlLocation(), USFOLKSERVICE_QNAME);
    }

    public UsFolkService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USFOLKSERVICE_QNAME, features);
    }

    public UsFolkService(URL wsdlLocation) {
        super(wsdlLocation, USFOLKSERVICE_QNAME);
    }

    public UsFolkService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USFOLKSERVICE_QNAME, features);
    }

    public UsFolkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsFolkService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsFolkPortType
     */
    @WebEndpoint(name = "UsFolkPort")
    public UsFolkPortType getUsFolkPort() {
        return super.getPort(new QName("http://us-folk-v3.x-road.eu/producer", "UsFolkPort"), UsFolkPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns UsFolkPortType
     */
    @WebEndpoint(name = "UsFolkPort")
    public UsFolkPortType getUsFolkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://us-folk-v3.x-road.eu/producer", "UsFolkPort"), UsFolkPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USFOLKSERVICE_EXCEPTION!= null) {
            throw USFOLKSERVICE_EXCEPTION;
        }
        return USFOLKSERVICE_WSDL_LOCATION;
    }

}
